# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class UpdateDriverRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, customer_id: str=None, phone: str=None, mail: str=None):  # noqa: E501
        """UpdateDriverRequest - a model defined in Swagger

        :param name: The name of this UpdateDriverRequest.  # noqa: E501
        :type name: str
        :param customer_id: The customer_id of this UpdateDriverRequest.  # noqa: E501
        :type customer_id: str
        :param phone: The phone of this UpdateDriverRequest.  # noqa: E501
        :type phone: str
        :param mail: The mail of this UpdateDriverRequest.  # noqa: E501
        :type mail: str
        """
        self.swagger_types = {
            'name': str,
            'customer_id': str,
            'phone': str,
            'mail': str
        }

        self.attribute_map = {
            'name': 'name',
            'customer_id': 'customerId',
            'phone': 'phone',
            'mail': 'mail'
        }
        self._name = name
        self._customer_id = customer_id
        self._phone = phone
        self._mail = mail

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateDriverRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateDriverRequest of this UpdateDriverRequest.  # noqa: E501
        :rtype: UpdateDriverRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UpdateDriverRequest.

        Complete Driver name  # noqa: E501

        :return: The name of this UpdateDriverRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UpdateDriverRequest.

        Complete Driver name  # noqa: E501

        :param name: The name of this UpdateDriverRequest.
        :type name: str
        """

        self._name = name

    @property
    def customer_id(self) -> str:
        """Gets the customer_id of this UpdateDriverRequest.


        :return: The customer_id of this UpdateDriverRequest.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: str):
        """Sets the customer_id of this UpdateDriverRequest.


        :param customer_id: The customer_id of this UpdateDriverRequest.
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def phone(self) -> str:
        """Gets the phone of this UpdateDriverRequest.

        Telephone number  # noqa: E501

        :return: The phone of this UpdateDriverRequest.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this UpdateDriverRequest.

        Telephone number  # noqa: E501

        :param phone: The phone of this UpdateDriverRequest.
        :type phone: str
        """

        self._phone = phone

    @property
    def mail(self) -> str:
        """Gets the mail of this UpdateDriverRequest.

        E-mail address  # noqa: E501

        :return: The mail of this UpdateDriverRequest.
        :rtype: str
        """
        return self._mail

    @mail.setter
    def mail(self, mail: str):
        """Sets the mail of this UpdateDriverRequest.

        E-mail address  # noqa: E501

        :param mail: The mail of this UpdateDriverRequest.
        :type mail: str
        """

        self._mail = mail
